In [ ]:
#without numpy 
data=[1,2,3,4,5]
result=[]
for i in data:
    result.append(i*2)
print(result)




[2, 4, 6, 8, 10]


In [2]:
import numpy as np
data=[1,2,3,4,5]
arr=np.array(data)
print(arr*2)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [10]:
import time
b=[1,2,"abc",True,3.4]
arr2=np.array(b)
print(arr2)

['1' '2' 'abc' 'True' '3.4']


In [15]:
arr=np.ones((2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
arr=np.linspace(0,100,12)
print(arr)

[  0.           9.09090909  18.18181818  27.27272727  36.36363636
  45.45454545  54.54545455  63.63636364  72.72727273  81.81818182
  90.90909091 100.        ]


In [27]:
arr=np.random.randint(10,50, size=(3,4))
print(arr)

[[38 44 28 44]
 [34 46 22 29]
 [24 21 40 12]]


In [30]:
import numpy as np
arr=np.array([1,2,3])
print(arr.dtype)
new_arr=arr.astype(float)
print(new_arr)
new_arr.dtype

int64
[1. 2. 3.]


dtype('float64')

In [15]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
print(arr.size)
min=arr.min()
print(min)
max=arr.max()
print(max)
print(arr.sum())
print(np.sum(arr,axis=0))#sum all the values in row and for column we use axis=1
print(arr.mean())
print(arr.std())
print(arr.argmax())
print(arr.argmin())


(2, 5)
10
1
10
55
[ 7  9 11 13 15]
5.5
2.8722813232690143
9
0


In [16]:
#Reshaping and Resizing.............
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [19]:
arr2=arr.reshape(6,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [21]:
arr2=np.resize(arr,(3,4))
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
#indexing and slicing............
arr=np.arange(11,30)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [23]:
arr[7]

np.int64(18)

In [25]:
arr[7:12]
arr[:8]


array([11, 12, 13, 14, 15, 16, 17, 18])

In [27]:
arr[4::2]

array([15, 17, 19, 21, 23, 25, 27, 29])

In [31]:

arr=np.arange(1,31).reshape(5,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [32]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [34]:
arr[4]

array([25, 26, 27, 28, 29, 30])

In [35]:
arr[2:5]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [36]:
arr[1,4]

np.int64(11)

In [37]:
arr[2:5,3:5]

array([[16, 17],
       [22, 23],
       [28, 29]])

In [38]:
arr[3:,3:]

array([[22, 23, 24],
       [28, 29, 30]])

In [43]:
arr=np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
arr[0]

array([1, 2, 3, 4, 5])

In [47]:
arr[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [48]:
arr[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [57]:
#artimatic operations............
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])




In [56]:
print("sum=" ,a1+a2)
print("sub=", a1-a2)
print("mul=",a1*a2)


sum= [ 7  9 11 13 15]
sub= [-5 -5 -5 -5 -5]
mul= [ 6 14 24 36 50]


In [2]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[11,22,33,44],[55,66,77,88]])

In [3]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
b

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [5]:
np.dot(a,b)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)