In [1]:

import numpy as np



---
## Exercise 1: Create a 1D Array

### Problem:
Create a NumPy array containing the numbers from **1 to 20** (inclusive).




In [2]:

arr = np.arange(1, 21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Exercise 2: Create a Matrix of Zeros 

### Problem:
Create a **5×5** matrix (2D array) filled with zeros.




In [3]:

import numpy as np
matrix = np.zeros((5, 5))
print(matrix)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Extract Specific Elements




In [4]:

import numpy as np
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

# 1. Element at [2, 3]
element = arr[2,3]
print('1. Element:', element)

# 2. Entire 3rd row
third_row = arr[2:3]
print('2. Third row:', third_row)

# 3. Entire 2nd column
second_col = arr[:,1:2]
print('3. Second column:', second_col)


1. Element: 120
2. Third row: [[ 90 100 110 120]]
3. Second column: [[ 20]
 [ 60]
 [100]]


## Exercise 4: Boolean Filtering 

### Problem:
Given the array of test scores below, find all scores that are **greater than or equal to 80**.

```


In [5]:

scores = np.array([75, 82, 90, 68, 85, 92, 78, 88, 95, 72])

passing_scores = scores[scores >= 80]

print('Passing scores (≥80):', passing_scores)


Passing scores (≥80): [82 90 85 92 88 95]


## Exercise 5: Calculate Statistics 

### Problem:
Given the array of daily temperatures, calculate:
1. The **mean** (average) temperature
2. The **maximum** temperature
3. The **minimum** temperature
4. The **standard deviation**

```python
temperatures = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])
```



In [6]:

temperatures = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])

mean_temp = np.mean(temperatures)
max_temp = np.max(temperatures)
min_temp = np.min(temperatures)
std_temp = np.std(temperatures)

print(f'Mean: {mean_temp}°F')
print(f'Max: {max_temp}°F')
print(f'Min: {min_temp}°F')
print(f'Std Dev: {std_temp:.2f}°F')


Mean: 76.6°F
Max: 82°F
Min: 72°F
Std Dev: 3.04°F


## Exercise 6: Reshape an Array 

### Problem:
Create an array of numbers from **1 to 12**, then reshape it into a **3×4** matrix.



In [7]:

arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Exercise 7: Element-wise Operations 



In [ ]:

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 25, 15, 35, 45])

# 1. Addition
sum_ab = a + b
print('1. Sum:', sum_ab)

# 2. Multiplication
product_ab = a * b
print('2. Product:', product_ab)

# 3. Comparison
comparison = a > b
print('3. a > b:', comparison)


1. Sum: [15 45 45 75 95]
2. Product: [  50  500  450 1400 2250]
3. a > b: [ True False  True  True  True]


## Exercise 8: Create a Random Array 

### Problem:
Create a **4×5** matrix of random integers between **1 and 100** (inclusive).




In [8]:


random_matrix = np.random.randint(1, 101, size=(4, 5))

print(random_matrix)
print('Shape:', random_matrix.shape)


[[89 43 51 83 39]
 [94  5 19 80 97]
 [77 83 62 20 87]
 [91 40 18 82 74]]
Shape: (4, 5)


## Exercise 9: Slice a Sub-array 

### Problem:
From the given matrix, extract the **center 2×2** sub-array.

```python
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
```




In [9]:

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

center = matrix[1:3, 1:3]

print(center)


[[ 6  7]
 [10 11]]


## Exercise 10: Broadcasting - Add a Row 

### Problem:
Add the array `[100, 200, 300]` to **each row** of the matrix below.




In [10]:

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

to_add = np.array([100, 200, 300])

result = matrix + to_add

print('Original:\n', matrix)
print('\nResult:\n', result)


Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Result:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


## Exercise 11: Dot Product

### Problem:
Calculate the **dot product** of these two arrays:

```python
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
```




In [11]:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

dot_product =  np.dot(a, b)

print('Dot product:', dot_product)


Dot product: 70


## Exercise 12: Normalize Data 

### Problem:
**Normalize** the array below:
- Formula: `(x - mean) / std_deviation`




In [12]:

data = np.array([10, 20, 30, 40, 50])

mean = np.mean(data)
std = np.std(data)

normalized = (data - mean) / std

print('Original:', data)
print('Normalized:', normalized)


Original: [10 20 30 40 50]
Normalized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## Exercise 13: Final Challenge - Student Grade Analysis 

### Problem:
Analyze student performance across 3 subjects:




In [13]:

grades = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 80],
                   [90, 92, 88],
                   [88, 86, 91]])




student_avg = np.mean(grades, axis=1)
print('1. Average per student:', student_avg)


subject_avg = np.mean(grades, axis=0)
print('2. Average per subject (Math, English, Science):', subject_avg)


highest_grade = np.max(grades)
print('3. Highest grade overall:', highest_grade)


best_student = np.argmax(student_avg)
print('4. Student with highest average (0-indexed):', best_student)

above_85_count = np.sum(grades > 85)
print('5. Grades above 85:', above_85_count)

1. Average per student: [84.33333333 91.66666667 81.         90.         88.33333333]
2. Average per subject (Math, English, Science): [86.6 88.2 86.4]
3. Highest grade overall: 95
4. Student with highest average (0-indexed): 1
5. Grades above 85: 10
